from probability.distributions.multivariate.dirichlet import Dirichlet
from probability.distributions.multivariate.multinomial import Multinomial
from probability.distributions.multivariate.mv_normal import MVNormal
